/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BonsaiRegistryEntry {
  'id' : bigint,
  'url' : string,
  'categories' : Array<Category>,
  'name' : string,
  'createdAt' : Time,
  'tier' : bigint,
  'ecosystem' : string,
  'description' : string,
  'logoUrl' : [] | [string],
}
export type Category = { 'nft' : null } |
  { 'tools' : null } |
  { 'social' : null } |
  { 'defi' : null } |
  { 'gaming' : null } |
  { 'wallet' : null } |
  { 'commerce' : null } |
  { 'exchange' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addRegistryEntry' : ActorMethod<[BonsaiRegistryEntry], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkImportEntries' : ActorMethod<
    [Array<BonsaiRegistryEntry>],
    Array<bigint>
  >,
  'fullTextSearch' : ActorMethod<
    [string, bigint, bigint],
    Array<BonsaiRegistryEntry>
  >,
  'getAllRegistryEntries' : ActorMethod<
    [bigint, bigint],
    Array<BonsaiRegistryEntry>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEntriesByCategory' : ActorMethod<
    [Category, bigint, bigint],
    Array<BonsaiRegistryEntry>
  >,
  'getEntriesByEcosystem' : ActorMethod<
    [string, bigint, bigint],
    Array<BonsaiRegistryEntry>
  >,
  'getTotalEntriesCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeRegistryEntry' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateRegistryEntry' : ActorMethod<[bigint, BonsaiRegistryEntry], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];