/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'nft' : IDL.Null,
  'tools' : IDL.Null,
  'social' : IDL.Null,
  'defi' : IDL.Null,
  'gaming' : IDL.Null,
  'wallet' : IDL.Null,
  'commerce' : IDL.Null,
  'exchange' : IDL.Null,
});
export const Time = IDL.Int;
export const BonsaiRegistryEntry = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'categories' : IDL.Vec(Category),
  'name' : IDL.Text,
  'createdAt' : Time,
  'tier' : IDL.Nat,
  'ecosystem' : IDL.Text,
  'description' : IDL.Text,
  'logoUrl' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EntryRatingStats = IDL.Record({
  'count' : IDL.Nat,
  'average' : IDL.Float64,
});
export const EmailSubscriber = IDL.Record({
  'subscribedAt' : Time,
  'source' : IDL.Text,
  'email' : IDL.Text,
  'principalId' : IDL.Opt(IDL.Text),
});
export const EntryRating = IDL.Record({
  'entryId' : IDL.Nat,
  'rating' : IDL.Nat,
});
export const SocialLinks = IDL.Record({
  'twitter' : IDL.Opt(IDL.Text),
  'website' : IDL.Opt(IDL.Text),
  'discord' : IDL.Opt(IDL.Text),
  'telegram' : IDL.Opt(IDL.Text),
  'github' : IDL.Opt(IDL.Text),
});
export const WalletAddresses = IDL.Record({
  'btc' : IDL.Opt(IDL.Text),
  'eth' : IDL.Opt(IDL.Text),
  'sol' : IDL.Opt(IDL.Text),
  'hbar' : IDL.Opt(IDL.Text),
});
export const ExtendedUserProfile = IDL.Record({
  'bio' : IDL.Text,
  'ratedEntries' : IDL.Vec(EntryRating),
  'submittedEntries' : IDL.Vec(IDL.Nat),
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'pinnedNfts' : IDL.Vec(
    IDL.Record({ 'tokenId' : IDL.Nat, 'collectionId' : IDL.Text })
  ),
  'socialLinks' : SocialLinks,
  'badges' : IDL.Vec(IDL.Text),
  'joinedAt' : Time,
  'walletAddresses' : WalletAddresses,
  'bookmarks' : IDL.Vec(IDL.Nat),
  'avatarUrl' : IDL.Opt(IDL.Text),
  'bannerUrl' : IDL.Opt(IDL.Text),
});
export const PendingSubmission = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'submitter' : IDL.Principal,
  'submittedAt' : Time,
  'entry' : BonsaiRegistryEntry,
  'paymentMemo' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRegistryEntry' : IDL.Func([BonsaiRegistryEntry], [IDL.Nat], []),
  'addRegistryEntryWithSecret' : IDL.Func(
      [IDL.Text, BonsaiRegistryEntry],
      [IDL.Nat],
      [],
    ),
  'approvePendingSubmissionWithSecret' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookmarkEntry' : IDL.Func([IDL.Nat], [], []),
  'bulkImportEntries' : IDL.Func(
      [IDL.Vec(BonsaiRegistryEntry)],
      [IDL.Vec(IDL.Nat)],
      [],
    ),
  'bulkImportEntriesWithSecret' : IDL.Func(
      [IDL.Text, IDL.Vec(BonsaiRegistryEntry)],
      [IDL.Vec(IDL.Nat)],
      [],
    ),
  'fullTextSearch' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(BonsaiRegistryEntry)],
      ['query'],
    ),
  'getAllBookmarkedEntries' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getAllEntryRatings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, EntryRatingStats))],
      ['query'],
    ),
  'getAllRegistryEntries' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(BonsaiRegistryEntry)],
      ['query'],
    ),
  'getAllSubscribersWithSecret' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(EmailSubscriber)],
      [],
    ),
  'getBannerAdsJson' : IDL.Func([], [IDL.Text], ['query']),
  'getEcosystemOrder' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerAllRatings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getCallerRating' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(ExtendedUserProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEntriesByCategory' : IDL.Func(
      [Category, IDL.Nat, IDL.Nat],
      [IDL.Vec(BonsaiRegistryEntry)],
      ['query'],
    ),
  'getEntriesByEcosystem' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(BonsaiRegistryEntry)],
      ['query'],
    ),
  'getEntryRating' : IDL.Func([IDL.Nat], [EntryRatingStats], ['query']),
  'getListingFee' : IDL.Func([], [IDL.Nat], ['query']),
  'getPendingSubmissions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PendingSubmission)],
      ['query'],
    ),
  'getPublicUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ExtendedUserProfile)],
      ['query'],
    ),
  'getSubscriberCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalEntriesCount' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'linkEmailToPrincipal' : IDL.Func([IDL.Text], [], []),
  'rateEntry' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'rejectPendingSubmissionWithSecret' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'removeRegistryEntry' : IDL.Func([IDL.Nat], [], []),
  'removeRegistryEntryWithSecret' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'saveBannerAdsWithSecret' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveEcosystemOrderWithSecret' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setListingFeeWithSecret' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'submitProjectListing' : IDL.Func(
      [BonsaiRegistryEntry, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'subscribeEmail' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'unbookmarkEntry' : IDL.Func([IDL.Nat], [], []),
  'updateRegistryEntry' : IDL.Func([IDL.Nat, BonsaiRegistryEntry], [], []),
  'updateRegistryEntryWithSecret' : IDL.Func(
      [IDL.Text, IDL.Nat, BonsaiRegistryEntry],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'nft' : IDL.Null,
    'tools' : IDL.Null,
    'social' : IDL.Null,
    'defi' : IDL.Null,
    'gaming' : IDL.Null,
    'wallet' : IDL.Null,
    'commerce' : IDL.Null,
    'exchange' : IDL.Null,
  });
  const Time = IDL.Int;
  const BonsaiRegistryEntry = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'categories' : IDL.Vec(Category),
    'name' : IDL.Text,
    'createdAt' : Time,
    'tier' : IDL.Nat,
    'ecosystem' : IDL.Text,
    'description' : IDL.Text,
    'logoUrl' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EntryRatingStats = IDL.Record({
    'count' : IDL.Nat,
    'average' : IDL.Float64,
  });
  const EmailSubscriber = IDL.Record({
    'subscribedAt' : Time,
    'source' : IDL.Text,
    'email' : IDL.Text,
    'principalId' : IDL.Opt(IDL.Text),
  });
  const EntryRating = IDL.Record({ 'entryId' : IDL.Nat, 'rating' : IDL.Nat });
  const SocialLinks = IDL.Record({
    'twitter' : IDL.Opt(IDL.Text),
    'website' : IDL.Opt(IDL.Text),
    'discord' : IDL.Opt(IDL.Text),
    'telegram' : IDL.Opt(IDL.Text),
    'github' : IDL.Opt(IDL.Text),
  });
  const WalletAddresses = IDL.Record({
    'btc' : IDL.Opt(IDL.Text),
    'eth' : IDL.Opt(IDL.Text),
    'sol' : IDL.Opt(IDL.Text),
    'hbar' : IDL.Opt(IDL.Text),
  });
  const ExtendedUserProfile = IDL.Record({
    'bio' : IDL.Text,
    'ratedEntries' : IDL.Vec(EntryRating),
    'submittedEntries' : IDL.Vec(IDL.Nat),
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'pinnedNfts' : IDL.Vec(
      IDL.Record({ 'tokenId' : IDL.Nat, 'collectionId' : IDL.Text })
    ),
    'socialLinks' : SocialLinks,
    'badges' : IDL.Vec(IDL.Text),
    'joinedAt' : Time,
    'walletAddresses' : WalletAddresses,
    'bookmarks' : IDL.Vec(IDL.Nat),
    'avatarUrl' : IDL.Opt(IDL.Text),
    'bannerUrl' : IDL.Opt(IDL.Text),
  });
  const PendingSubmission = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'submitter' : IDL.Principal,
    'submittedAt' : Time,
    'entry' : BonsaiRegistryEntry,
    'paymentMemo' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRegistryEntry' : IDL.Func([BonsaiRegistryEntry], [IDL.Nat], []),
    'addRegistryEntryWithSecret' : IDL.Func(
        [IDL.Text, BonsaiRegistryEntry],
        [IDL.Nat],
        [],
      ),
    'approvePendingSubmissionWithSecret' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookmarkEntry' : IDL.Func([IDL.Nat], [], []),
    'bulkImportEntries' : IDL.Func(
        [IDL.Vec(BonsaiRegistryEntry)],
        [IDL.Vec(IDL.Nat)],
        [],
      ),
    'bulkImportEntriesWithSecret' : IDL.Func(
        [IDL.Text, IDL.Vec(BonsaiRegistryEntry)],
        [IDL.Vec(IDL.Nat)],
        [],
      ),
    'fullTextSearch' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(BonsaiRegistryEntry)],
        ['query'],
      ),
    'getAllBookmarkedEntries' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getAllEntryRatings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, EntryRatingStats))],
        ['query'],
      ),
    'getAllRegistryEntries' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(BonsaiRegistryEntry)],
        ['query'],
      ),
    'getAllSubscribersWithSecret' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(EmailSubscriber)],
        [],
      ),
    'getBannerAdsJson' : IDL.Func([], [IDL.Text], ['query']),
    'getEcosystemOrder' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerAllRatings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getCallerRating' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(ExtendedUserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEntriesByCategory' : IDL.Func(
        [Category, IDL.Nat, IDL.Nat],
        [IDL.Vec(BonsaiRegistryEntry)],
        ['query'],
      ),
    'getEntriesByEcosystem' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(BonsaiRegistryEntry)],
        ['query'],
      ),
    'getEntryRating' : IDL.Func([IDL.Nat], [EntryRatingStats], ['query']),
    'getListingFee' : IDL.Func([], [IDL.Nat], ['query']),
    'getPendingSubmissions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PendingSubmission)],
        ['query'],
      ),
    'getPublicUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ExtendedUserProfile)],
        ['query'],
      ),
    'getSubscriberCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalEntriesCount' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'linkEmailToPrincipal' : IDL.Func([IDL.Text], [], []),
    'rateEntry' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'rejectPendingSubmissionWithSecret' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'removeRegistryEntry' : IDL.Func([IDL.Nat], [], []),
    'removeRegistryEntryWithSecret' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'saveBannerAdsWithSecret' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveEcosystemOrderWithSecret' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([ExtendedUserProfile], [], []),
    'setListingFeeWithSecret' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'submitProjectListing' : IDL.Func(
        [BonsaiRegistryEntry, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'subscribeEmail' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'unbookmarkEntry' : IDL.Func([IDL.Nat], [], []),
    'updateRegistryEntry' : IDL.Func([IDL.Nat, BonsaiRegistryEntry], [], []),
    'updateRegistryEntryWithSecret' : IDL.Func(
        [IDL.Text, IDL.Nat, BonsaiRegistryEntry],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };