/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BonsaiRegistryEntry {
  'id' : bigint,
  'url' : string,
  'categories' : Array<Category>,
  'name' : string,
  'createdAt' : Time,
  'tier' : bigint,
  'ecosystem' : string,
  'description' : string,
  'logoUrl' : [] | [string],
}
export type Category = { 'nft' : null } |
  { 'tools' : null } |
  { 'social' : null } |
  { 'defi' : null } |
  { 'gaming' : null } |
  { 'wallet' : null } |
  { 'commerce' : null } |
  { 'exchange' : null };
export interface EmailSubscriber {
  'subscribedAt' : Time,
  'source' : string,
  'email' : string,
  'principalId' : [] | [string],
}
export interface EntryRating { 'entryId' : bigint, 'rating' : bigint }
export interface EntryRatingStats { 'count' : bigint, 'average' : number }
export interface ExtendedUserProfile {
  'bio' : string,
  'ratedEntries' : Array<EntryRating>,
  'submittedEntries' : Array<bigint>,
  'username' : string,
  'displayName' : string,
  'pinnedNfts' : Array<{ 'tokenId' : bigint, 'collectionId' : string }>,
  'socialLinks' : SocialLinks,
  'badges' : Array<string>,
  'joinedAt' : Time,
  'walletAddresses' : WalletAddresses,
  'bookmarks' : Array<bigint>,
  'avatarUrl' : [] | [string],
  'bannerUrl' : [] | [string],
}
export interface PendingSubmission {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'submitter' : Principal,
  'submittedAt' : Time,
  'entry' : BonsaiRegistryEntry,
  'paymentMemo' : string,
}
export interface SocialLinks {
  'twitter' : [] | [string],
  'website' : [] | [string],
  'discord' : [] | [string],
  'telegram' : [] | [string],
  'github' : [] | [string],
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WalletAddresses {
  'btc' : [] | [string],
  'eth' : [] | [string],
  'sol' : [] | [string],
  'hbar' : [] | [string],
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addRegistryEntry' : ActorMethod<[BonsaiRegistryEntry], bigint>,
  'addRegistryEntryWithSecret' : ActorMethod<
    [string, BonsaiRegistryEntry],
    bigint
  >,
  'approvePendingSubmissionWithSecret' : ActorMethod<
    [string, bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookmarkEntry' : ActorMethod<[bigint], undefined>,
  'bulkImportEntries' : ActorMethod<
    [Array<BonsaiRegistryEntry>],
    Array<bigint>
  >,
  'bulkImportEntriesWithSecret' : ActorMethod<
    [string, Array<BonsaiRegistryEntry>],
    Array<bigint>
  >,
  'fullTextSearch' : ActorMethod<
    [string, bigint, bigint],
    Array<BonsaiRegistryEntry>
  >,
  'getAllBookmarkedEntries' : ActorMethod<[], Array<bigint>>,
  'getAllEntryRatings' : ActorMethod<[], Array<[bigint, EntryRatingStats]>>,
  'getAllRegistryEntries' : ActorMethod<
    [bigint, bigint],
    Array<BonsaiRegistryEntry>
  >,
  'getAllSubscribersWithSecret' : ActorMethod<[string], Array<EmailSubscriber>>,
  'getBannerAdsJson' : ActorMethod<[], string>,
  'getEcosystemOrder' : ActorMethod<[], string>,
  'getCallerAllRatings' : ActorMethod<[], Array<[bigint, bigint]>>,
  'getCallerRating' : ActorMethod<[bigint], [] | [bigint]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [ExtendedUserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEntriesByCategory' : ActorMethod<
    [Category, bigint, bigint],
    Array<BonsaiRegistryEntry>
  >,
  'getEntriesByEcosystem' : ActorMethod<
    [string, bigint, bigint],
    Array<BonsaiRegistryEntry>
  >,
  'getEntryRating' : ActorMethod<[bigint], EntryRatingStats>,
  'getListingFee' : ActorMethod<[], bigint>,
  'getPendingSubmissions' : ActorMethod<[string], Array<PendingSubmission>>,
  'getPublicUserProfile' : ActorMethod<[Principal], [] | [ExtendedUserProfile]>,
  'getSubscriberCount' : ActorMethod<[], bigint>,
  'getTotalEntriesCount' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'linkEmailToPrincipal' : ActorMethod<[string], undefined>,
  'rateEntry' : ActorMethod<[bigint, bigint], undefined>,
  'rejectPendingSubmissionWithSecret' : ActorMethod<
    [string, bigint],
    undefined
  >,
  'removeRegistryEntry' : ActorMethod<[bigint], undefined>,
  'removeRegistryEntryWithSecret' : ActorMethod<[string, bigint], undefined>,
  'saveBannerAdsWithSecret' : ActorMethod<[string, string], undefined>,
  'saveEcosystemOrderWithSecret' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[ExtendedUserProfile], undefined>,
  'setListingFeeWithSecret' : ActorMethod<[string, bigint], undefined>,
  'submitProjectListing' : ActorMethod<[BonsaiRegistryEntry, string], bigint>,
  'subscribeEmail' : ActorMethod<[string, string, string], undefined>,
  'unbookmarkEntry' : ActorMethod<[bigint], undefined>,
  'updateRegistryEntry' : ActorMethod<[bigint, BonsaiRegistryEntry], undefined>,
  'updateRegistryEntryWithSecret' : ActorMethod<
    [string, bigint, BonsaiRegistryEntry],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];