/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'nft' : IDL.Null,
  'tools' : IDL.Null,
  'social' : IDL.Null,
  'defi' : IDL.Null,
  'gaming' : IDL.Null,
  'wallet' : IDL.Null,
  'commerce' : IDL.Null,
  'exchange' : IDL.Null,
});
export const Time = IDL.Int;
export const BonsaiRegistryEntry = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'categories' : IDL.Vec(Category),
  'name' : IDL.Text,
  'createdAt' : Time,
  'tier' : IDL.Nat,
  'ecosystem' : IDL.Text,
  'description' : IDL.Text,
  'logoUrl' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRegistryEntry' : IDL.Func([BonsaiRegistryEntry], [IDL.Nat], []),
  'addRegistryEntryWithSecret' : IDL.Func(
      [IDL.Text, BonsaiRegistryEntry],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkImportEntries' : IDL.Func(
      [IDL.Vec(BonsaiRegistryEntry)],
      [IDL.Vec(IDL.Nat)],
      [],
    ),
  'bulkImportEntriesWithSecret' : IDL.Func(
      [IDL.Text, IDL.Vec(BonsaiRegistryEntry)],
      [IDL.Vec(IDL.Nat)],
      [],
    ),
  'fullTextSearch' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(BonsaiRegistryEntry)],
      ['query'],
    ),
  'getAllRegistryEntries' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(BonsaiRegistryEntry)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEntriesByCategory' : IDL.Func(
      [Category, IDL.Nat, IDL.Nat],
      [IDL.Vec(BonsaiRegistryEntry)],
      ['query'],
    ),
  'getEntriesByEcosystem' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(BonsaiRegistryEntry)],
      ['query'],
    ),
  'getTotalEntriesCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeRegistryEntry' : IDL.Func([IDL.Nat], [], []),
  'removeRegistryEntryWithSecret' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateRegistryEntry' : IDL.Func([IDL.Nat, BonsaiRegistryEntry], [], []),
  'updateRegistryEntryWithSecret' : IDL.Func(
      [IDL.Text, IDL.Nat, BonsaiRegistryEntry],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'nft' : IDL.Null,
    'tools' : IDL.Null,
    'social' : IDL.Null,
    'defi' : IDL.Null,
    'gaming' : IDL.Null,
    'wallet' : IDL.Null,
    'commerce' : IDL.Null,
    'exchange' : IDL.Null,
  });
  const Time = IDL.Int;
  const BonsaiRegistryEntry = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'categories' : IDL.Vec(Category),
    'name' : IDL.Text,
    'createdAt' : Time,
    'tier' : IDL.Nat,
    'ecosystem' : IDL.Text,
    'description' : IDL.Text,
    'logoUrl' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRegistryEntry' : IDL.Func([BonsaiRegistryEntry], [IDL.Nat], []),
    'addRegistryEntryWithSecret' : IDL.Func(
        [IDL.Text, BonsaiRegistryEntry],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkImportEntries' : IDL.Func(
        [IDL.Vec(BonsaiRegistryEntry)],
        [IDL.Vec(IDL.Nat)],
        [],
      ),
    'bulkImportEntriesWithSecret' : IDL.Func(
        [IDL.Text, IDL.Vec(BonsaiRegistryEntry)],
        [IDL.Vec(IDL.Nat)],
        [],
      ),
    'fullTextSearch' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(BonsaiRegistryEntry)],
        ['query'],
      ),
    'getAllRegistryEntries' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(BonsaiRegistryEntry)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEntriesByCategory' : IDL.Func(
        [Category, IDL.Nat, IDL.Nat],
        [IDL.Vec(BonsaiRegistryEntry)],
        ['query'],
      ),
    'getEntriesByEcosystem' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(BonsaiRegistryEntry)],
        ['query'],
      ),
    'getTotalEntriesCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeRegistryEntry' : IDL.Func([IDL.Nat], [], []),
    'removeRegistryEntryWithSecret' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateRegistryEntry' : IDL.Func([IDL.Nat, BonsaiRegistryEntry], [], []),
    'updateRegistryEntryWithSecret' : IDL.Func(
        [IDL.Text, IDL.Nat, BonsaiRegistryEntry],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };