/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BonsaiRegistryEntry {
    id: bigint;
    url: string;
    categories: Array<Category>;
    name: string;
    createdAt: Time;
    tier: bigint;
    ecosystem: string;
    description: string;
    logoUrl?: string;
}
export type Time = bigint;
export interface UserProfile {
    name: string;
}
export enum Category {
    nft = "nft",
    tools = "tools",
    social = "social",
    defi = "defi",
    gaming = "gaming",
    wallet = "wallet",
    commerce = "commerce",
    exchange = "exchange"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addRegistryEntry(entry: BonsaiRegistryEntry): Promise<bigint>;
    addRegistryEntryWithSecret(secret: string, entry: BonsaiRegistryEntry): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkImportEntries(entries: Array<BonsaiRegistryEntry>): Promise<Array<bigint>>;
    bulkImportEntriesWithSecret(secret: string, entries: Array<BonsaiRegistryEntry>): Promise<Array<bigint>>;
    fullTextSearch(arg0: string, arg1: bigint, arg2: bigint): Promise<Array<BonsaiRegistryEntry>>;
    getAllRegistryEntries(offset: bigint, limit: bigint): Promise<Array<BonsaiRegistryEntry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEntriesByCategory(category: Category, offset: bigint, limit: bigint): Promise<Array<BonsaiRegistryEntry>>;
    getEntriesByEcosystem(ecosystem: string, offset: bigint, limit: bigint): Promise<Array<BonsaiRegistryEntry>>;
    getTotalEntriesCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeRegistryEntry(id: bigint): Promise<void>;
    removeRegistryEntryWithSecret(secret: string, id: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateRegistryEntry(id: bigint, newEntry: BonsaiRegistryEntry): Promise<void>;
    updateRegistryEntryWithSecret(secret: string, id: bigint, newEntry: BonsaiRegistryEntry): Promise<void>;
}
import type { BonsaiRegistryEntry as _BonsaiRegistryEntry, Category as _Category, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addRegistryEntry(arg0: BonsaiRegistryEntry): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addRegistryEntry(to_candid_BonsaiRegistryEntry_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRegistryEntry(to_candid_BonsaiRegistryEntry_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addRegistryEntryWithSecret(arg0: string, arg1: BonsaiRegistryEntry): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addRegistryEntryWithSecret(arg0, to_candid_BonsaiRegistryEntry_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRegistryEntryWithSecret(arg0, to_candid_BonsaiRegistryEntry_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkImportEntries(arg0: Array<BonsaiRegistryEntry>): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkImportEntries(to_candid_vec_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkImportEntries(to_candid_vec_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async bulkImportEntriesWithSecret(arg0: string, arg1: Array<BonsaiRegistryEntry>): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkImportEntriesWithSecret(arg0, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkImportEntriesWithSecret(arg0, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async fullTextSearch(arg0: string, arg1: bigint, arg2: bigint): Promise<Array<BonsaiRegistryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.fullTextSearch(arg0, arg1, arg2);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fullTextSearch(arg0, arg1, arg2);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRegistryEntries(arg0: bigint, arg1: bigint): Promise<Array<BonsaiRegistryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRegistryEntries(arg0, arg1);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRegistryEntries(arg0, arg1);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEntriesByCategory(arg0: Category, arg1: bigint, arg2: bigint): Promise<Array<BonsaiRegistryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntriesByCategory(to_candid_Category_n4(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntriesByCategory(to_candid_Category_n4(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEntriesByEcosystem(arg0: string, arg1: bigint, arg2: bigint): Promise<Array<BonsaiRegistryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntriesByEcosystem(arg0, arg1, arg2);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntriesByEcosystem(arg0, arg1, arg2);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalEntriesCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalEntriesCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalEntriesCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeRegistryEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeRegistryEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeRegistryEntry(arg0);
            return result;
        }
    }
    async removeRegistryEntryWithSecret(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeRegistryEntryWithSecret(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeRegistryEntryWithSecret(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateRegistryEntry(arg0: bigint, arg1: BonsaiRegistryEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRegistryEntry(arg0, to_candid_BonsaiRegistryEntry_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRegistryEntry(arg0, to_candid_BonsaiRegistryEntry_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateRegistryEntryWithSecret(arg0: string, arg1: bigint, arg2: BonsaiRegistryEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRegistryEntryWithSecret(arg0, arg1, to_candid_BonsaiRegistryEntry_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRegistryEntryWithSecret(arg0, arg1, to_candid_BonsaiRegistryEntry_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_BonsaiRegistryEntry_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BonsaiRegistryEntry): BonsaiRegistryEntry {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    url: string;
    categories: Array<_Category>;
    name: string;
    createdAt: _Time;
    tier: bigint;
    ecosystem: string;
    description: string;
    logoUrl: [] | [string];
}): {
    id: bigint;
    url: string;
    categories: Array<Category>;
    name: string;
    createdAt: Time;
    tier: bigint;
    ecosystem: string;
    description: string;
    logoUrl?: string;
} {
    return {
        id: value.id,
        url: value.url,
        categories: from_candid_vec_n12(_uploadFile, _downloadFile, value.categories),
        name: value.name,
        createdAt: value.createdAt,
        tier: value.tier,
        ecosystem: value.ecosystem,
        description: value.description,
        logoUrl: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.logoUrl))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nft: null;
} | {
    tools: null;
} | {
    social: null;
} | {
    defi: null;
} | {
    gaming: null;
} | {
    wallet: null;
} | {
    commerce: null;
} | {
    exchange: null;
}): Category {
    return "nft" in value ? Category.nft : "tools" in value ? Category.tools : "social" in value ? Category.social : "defi" in value ? Category.defi : "gaming" in value ? Category.gaming : "wallet" in value ? Category.wallet : "commerce" in value ? Category.commerce : "exchange" in value ? Category.exchange : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Category>): Array<Category> {
    return value.map((x)=>from_candid_Category_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BonsaiRegistryEntry>): Array<BonsaiRegistryEntry> {
    return value.map((x)=>from_candid_BonsaiRegistryEntry_n10(_uploadFile, _downloadFile, x));
}
function to_candid_BonsaiRegistryEntry_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BonsaiRegistryEntry): _BonsaiRegistryEntry {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    url: string;
    categories: Array<Category>;
    name: string;
    createdAt: Time;
    tier: bigint;
    ecosystem: string;
    description: string;
    logoUrl?: string;
}): {
    id: bigint;
    url: string;
    categories: Array<_Category>;
    name: string;
    createdAt: _Time;
    tier: bigint;
    ecosystem: string;
    description: string;
    logoUrl: [] | [string];
} {
    return {
        id: value.id,
        url: value.url,
        categories: to_candid_vec_n3(_uploadFile, _downloadFile, value.categories),
        name: value.name,
        createdAt: value.createdAt,
        tier: value.tier,
        ecosystem: value.ecosystem,
        description: value.description,
        logoUrl: value.logoUrl ? candid_some(value.logoUrl) : candid_none()
    };
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    nft: null;
} | {
    tools: null;
} | {
    social: null;
} | {
    defi: null;
} | {
    gaming: null;
} | {
    wallet: null;
} | {
    commerce: null;
} | {
    exchange: null;
} {
    return value == Category.nft ? {
        nft: null
    } : value == Category.tools ? {
        tools: null
    } : value == Category.social ? {
        social: null
    } : value == Category.defi ? {
        defi: null
    } : value == Category.gaming ? {
        gaming: null
    } : value == Category.wallet ? {
        wallet: null
    } : value == Category.commerce ? {
        commerce: null
    } : value == Category.exchange ? {
        exchange: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Category>): Array<_Category> {
    return value.map((x)=>to_candid_Category_n4(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<BonsaiRegistryEntry>): Array<_BonsaiRegistryEntry> {
    return value.map((x)=>to_candid_BonsaiRegistryEntry_n1(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
