/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ExtendedUserProfile {
    bio: string;
    ratedEntries: Array<EntryRating>;
    submittedEntries: Array<bigint>;
    username: string;
    displayName: string;
    pinnedNfts: Array<{
        tokenId: bigint;
        collectionId: string;
    }>;
    socialLinks: SocialLinks;
    badges: Array<string>;
    joinedAt: Time;
    walletAddresses: WalletAddresses;
    bookmarks: Array<bigint>;
    avatarUrl?: string;
    bannerUrl?: string;
}
export type Time = bigint;
export interface WalletAddresses {
    btc?: string;
    eth?: string;
    sol?: string;
    hbar?: string;
}
export interface SocialLinks {
    twitter?: string;
    website?: string;
    discord?: string;
    telegram?: string;
    github?: string;
}
export interface PendingSubmission {
    id: bigint;
    status: Variant_pending_approved_rejected;
    submitter: Principal;
    submittedAt: Time;
    entry: BonsaiRegistryEntry;
    paymentMemo: string;
}
export interface EmailSubscriber {
    subscribedAt: Time;
    source: string;
    email: string;
    principalId?: string;
}
export interface BonsaiRegistryEntry {
    id: bigint;
    url: string;
    categories: Array<Category>;
    name: string;
    createdAt: Time;
    tier: bigint;
    ecosystem: string;
    description: string;
    logoUrl?: string;
}
export interface EntryRatingStats {
    count: bigint;
    average: number;
}
export interface EntryRating {
    entryId: bigint;
    rating: bigint;
}
export enum Category {
    nft = "nft",
    tools = "tools",
    social = "social",
    defi = "defi",
    gaming = "gaming",
    wallet = "wallet",
    commerce = "commerce",
    exchange = "exchange"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addRegistryEntry(entry: BonsaiRegistryEntry): Promise<bigint>;
    addRegistryEntryWithSecret(secret: string, entry: BonsaiRegistryEntry): Promise<bigint>;
    approvePendingSubmissionWithSecret(secret: string, submissionId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookmarkEntry(entryId: bigint): Promise<void>;
    bulkImportEntries(entries: Array<BonsaiRegistryEntry>): Promise<Array<bigint>>;
    bulkImportEntriesWithSecret(secret: string, entries: Array<BonsaiRegistryEntry>): Promise<Array<bigint>>;
    fullTextSearch(arg0: string, arg1: bigint, arg2: bigint): Promise<Array<BonsaiRegistryEntry>>;
    getAllBookmarkedEntries(): Promise<Array<bigint>>;
    getAllEntryRatings(): Promise<Array<[bigint, EntryRatingStats]>>;
    getAllRegistryEntries(offset: bigint, limit: bigint): Promise<Array<BonsaiRegistryEntry>>;
    getAllSubscribersWithSecret(secret: string): Promise<Array<EmailSubscriber>>;
    getBannerAdsJson(): Promise<string>;
    getEcosystemOrder(): Promise<string>;
    getCallerAllRatings(): Promise<Array<[bigint, bigint]>>;
    getCallerRating(entryId: bigint): Promise<bigint | null>;
    getCallerUserProfile(): Promise<ExtendedUserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEntriesByCategory(category: Category, offset: bigint, limit: bigint): Promise<Array<BonsaiRegistryEntry>>;
    getEntriesByEcosystem(ecosystem: string, offset: bigint, limit: bigint): Promise<Array<BonsaiRegistryEntry>>;
    getEntryRating(entryId: bigint): Promise<EntryRatingStats>;
    getListingFee(): Promise<bigint>;
    getPendingSubmissions(secret: string): Promise<Array<PendingSubmission>>;
    getPublicUserProfile(user: Principal): Promise<ExtendedUserProfile | null>;
    getSubscriberCount(): Promise<bigint>;
    getTotalEntriesCount(): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    linkEmailToPrincipal(email: string): Promise<void>;
    rateEntry(entryId: bigint, rating: bigint): Promise<void>;
    rejectPendingSubmissionWithSecret(secret: string, submissionId: bigint): Promise<void>;
    removeRegistryEntry(id: bigint): Promise<void>;
    removeRegistryEntryWithSecret(secret: string, id: bigint): Promise<void>;
    saveBannerAdsWithSecret(secret: string, adsJson: string): Promise<void>;
    saveEcosystemOrderWithSecret(secret: string, orderJson: string): Promise<void>;
    saveCallerUserProfile(profile: ExtendedUserProfile): Promise<void>;
    setListingFeeWithSecret(secret: string, fee: bigint): Promise<void>;
    submitProjectListing(entry: BonsaiRegistryEntry, paymentMemo: string): Promise<bigint>;
    subscribeEmail(email: string, oisyPrincipal: string, source: string): Promise<void>;
    unbookmarkEntry(entryId: bigint): Promise<void>;
    updateRegistryEntry(id: bigint, newEntry: BonsaiRegistryEntry): Promise<void>;
    updateRegistryEntryWithSecret(secret: string, id: bigint, newEntry: BonsaiRegistryEntry): Promise<void>;
}
import type { BonsaiRegistryEntry as _BonsaiRegistryEntry, Category as _Category, EmailSubscriber as _EmailSubscriber, EntryRating as _EntryRating, ExtendedUserProfile as _ExtendedUserProfile, PendingSubmission as _PendingSubmission, SocialLinks as _SocialLinks, Time as _Time, UserRole as _UserRole, WalletAddresses as _WalletAddresses } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addRegistryEntry(arg0: BonsaiRegistryEntry): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addRegistryEntry(to_candid_BonsaiRegistryEntry_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRegistryEntry(to_candid_BonsaiRegistryEntry_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addRegistryEntryWithSecret(arg0: string, arg1: BonsaiRegistryEntry): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addRegistryEntryWithSecret(arg0, to_candid_BonsaiRegistryEntry_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRegistryEntryWithSecret(arg0, to_candid_BonsaiRegistryEntry_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async approvePendingSubmissionWithSecret(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approvePendingSubmissionWithSecret(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approvePendingSubmissionWithSecret(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookmarkEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bookmarkEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookmarkEntry(arg0);
            return result;
        }
    }
    async bulkImportEntries(arg0: Array<BonsaiRegistryEntry>): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkImportEntries(to_candid_vec_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkImportEntries(to_candid_vec_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async bulkImportEntriesWithSecret(arg0: string, arg1: Array<BonsaiRegistryEntry>): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkImportEntriesWithSecret(arg0, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkImportEntriesWithSecret(arg0, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async fullTextSearch(arg0: string, arg1: bigint, arg2: bigint): Promise<Array<BonsaiRegistryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.fullTextSearch(arg0, arg1, arg2);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fullTextSearch(arg0, arg1, arg2);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBookmarkedEntries(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookmarkedEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookmarkedEntries();
            return result;
        }
    }
    async getAllEntryRatings(): Promise<Array<[bigint, EntryRatingStats]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEntryRatings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEntryRatings();
            return result;
        }
    }
    async getAllRegistryEntries(arg0: bigint, arg1: bigint): Promise<Array<BonsaiRegistryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRegistryEntries(arg0, arg1);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRegistryEntries(arg0, arg1);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSubscribersWithSecret(arg0: string): Promise<Array<EmailSubscriber>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubscribersWithSecret(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubscribersWithSecret(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBannerAdsJson(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getBannerAdsJson();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBannerAdsJson();
            return result;
        }
    }
    async getEcosystemOrder(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getEcosystemOrder();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEcosystemOrder();
            return result;
        }
    }
    async getCallerAllRatings(): Promise<Array<[bigint, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerAllRatings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerAllRatings();
            return result;
        }
    }
    async getCallerRating(arg0: bigint): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerRating(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerRating(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<ExtendedUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEntriesByCategory(arg0: Category, arg1: bigint, arg2: bigint): Promise<Array<BonsaiRegistryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntriesByCategory(to_candid_Category_n4(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntriesByCategory(to_candid_Category_n4(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEntriesByEcosystem(arg0: string, arg1: bigint, arg2: bigint): Promise<Array<BonsaiRegistryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntriesByEcosystem(arg0, arg1, arg2);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntriesByEcosystem(arg0, arg1, arg2);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEntryRating(arg0: bigint): Promise<EntryRatingStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntryRating(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntryRating(arg0);
            return result;
        }
    }
    async getListingFee(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingFee();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingFee();
            return result;
        }
    }
    async getPendingSubmissions(arg0: string): Promise<Array<PendingSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingSubmissions(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingSubmissions(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicUserProfile(arg0: Principal): Promise<ExtendedUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscriberCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriberCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriberCount();
            return result;
        }
    }
    async getTotalEntriesCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalEntriesCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalEntriesCount();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async linkEmailToPrincipal(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.linkEmailToPrincipal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkEmailToPrincipal(arg0);
            return result;
        }
    }
    async rateEntry(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rateEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rateEntry(arg0, arg1);
            return result;
        }
    }
    async rejectPendingSubmissionWithSecret(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectPendingSubmissionWithSecret(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectPendingSubmissionWithSecret(arg0, arg1);
            return result;
        }
    }
    async removeRegistryEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeRegistryEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeRegistryEntry(arg0);
            return result;
        }
    }
    async removeRegistryEntryWithSecret(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeRegistryEntryWithSecret(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeRegistryEntryWithSecret(arg0, arg1);
            return result;
        }
    }
    async saveBannerAdsWithSecret(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBannerAdsWithSecret(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBannerAdsWithSecret(arg0, arg1);
            return result;
        }
    }
    async saveEcosystemOrderWithSecret(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveEcosystemOrderWithSecret(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveEcosystemOrderWithSecret(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: ExtendedUserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_ExtendedUserProfile_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_ExtendedUserProfile_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setListingFeeWithSecret(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setListingFeeWithSecret(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setListingFeeWithSecret(arg0, arg1);
            return result;
        }
    }
    async submitProjectListing(arg0: BonsaiRegistryEntry, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitProjectListing(to_candid_BonsaiRegistryEntry_n1(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitProjectListing(to_candid_BonsaiRegistryEntry_n1(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async subscribeEmail(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribeEmail(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribeEmail(arg0, arg1, arg2);
            return result;
        }
    }
    async unbookmarkEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unbookmarkEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unbookmarkEntry(arg0);
            return result;
        }
    }
    async updateRegistryEntry(arg0: bigint, arg1: BonsaiRegistryEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRegistryEntry(arg0, to_candid_BonsaiRegistryEntry_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRegistryEntry(arg0, to_candid_BonsaiRegistryEntry_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateRegistryEntryWithSecret(arg0: string, arg1: bigint, arg2: BonsaiRegistryEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRegistryEntryWithSecret(arg0, arg1, to_candid_BonsaiRegistryEntry_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRegistryEntryWithSecret(arg0, arg1, to_candid_BonsaiRegistryEntry_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_BonsaiRegistryEntry_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BonsaiRegistryEntry): BonsaiRegistryEntry {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_EmailSubscriber_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmailSubscriber): EmailSubscriber {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ExtendedUserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExtendedUserProfile): ExtendedUserProfile {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PendingSubmission_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PendingSubmission): PendingSubmission {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_SocialLinks_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SocialLinks): SocialLinks {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_WalletAddresses_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WalletAddresses): WalletAddresses {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExtendedUserProfile]): ExtendedUserProfile | null {
    return value.length === 0 ? null : from_candid_ExtendedUserProfile_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    url: string;
    categories: Array<_Category>;
    name: string;
    createdAt: _Time;
    tier: bigint;
    ecosystem: string;
    description: string;
    logoUrl: [] | [string];
}): {
    id: bigint;
    url: string;
    categories: Array<Category>;
    name: string;
    createdAt: Time;
    tier: bigint;
    ecosystem: string;
    description: string;
    logoUrl?: string;
} {
    return {
        id: value.id,
        url: value.url,
        categories: from_candid_vec_n12(_uploadFile, _downloadFile, value.categories),
        name: value.name,
        createdAt: value.createdAt,
        tier: value.tier,
        ecosystem: value.ecosystem,
        description: value.description,
        logoUrl: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.logoUrl))
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subscribedAt: _Time;
    source: string;
    email: string;
    principalId: [] | [string];
}): {
    subscribedAt: Time;
    source: string;
    email: string;
    principalId?: string;
} {
    return {
        subscribedAt: value.subscribedAt,
        source: value.source,
        email: value.email,
        principalId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.principalId))
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    ratedEntries: Array<_EntryRating>;
    submittedEntries: Array<bigint>;
    username: string;
    displayName: string;
    pinnedNfts: Array<{
        tokenId: bigint;
        collectionId: string;
    }>;
    socialLinks: _SocialLinks;
    badges: Array<string>;
    joinedAt: _Time;
    walletAddresses: _WalletAddresses;
    bookmarks: Array<bigint>;
    avatarUrl: [] | [string];
    bannerUrl: [] | [string];
}): {
    bio: string;
    ratedEntries: Array<EntryRating>;
    submittedEntries: Array<bigint>;
    username: string;
    displayName: string;
    pinnedNfts: Array<{
        tokenId: bigint;
        collectionId: string;
    }>;
    socialLinks: SocialLinks;
    badges: Array<string>;
    joinedAt: Time;
    walletAddresses: WalletAddresses;
    bookmarks: Array<bigint>;
    avatarUrl?: string;
    bannerUrl?: string;
} {
    return {
        bio: value.bio,
        ratedEntries: value.ratedEntries,
        submittedEntries: value.submittedEntries,
        username: value.username,
        displayName: value.displayName,
        pinnedNfts: value.pinnedNfts,
        socialLinks: from_candid_SocialLinks_n23(_uploadFile, _downloadFile, value.socialLinks),
        badges: value.badges,
        joinedAt: value.joinedAt,
        walletAddresses: from_candid_WalletAddresses_n25(_uploadFile, _downloadFile, value.walletAddresses),
        bookmarks: value.bookmarks,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.avatarUrl)),
        bannerUrl: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.bannerUrl))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    twitter: [] | [string];
    website: [] | [string];
    discord: [] | [string];
    telegram: [] | [string];
    github: [] | [string];
}): {
    twitter?: string;
    website?: string;
    discord?: string;
    telegram?: string;
    github?: string;
} {
    return {
        twitter: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.twitter)),
        website: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.website)),
        discord: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.discord)),
        telegram: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.telegram)),
        github: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.github))
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    btc: [] | [string];
    eth: [] | [string];
    sol: [] | [string];
    hbar: [] | [string];
}): {
    btc?: string;
    eth?: string;
    sol?: string;
    hbar?: string;
} {
    return {
        btc: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.btc)),
        eth: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.eth)),
        sol: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.sol)),
        hbar: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.hbar))
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    submitter: Principal;
    submittedAt: _Time;
    entry: _BonsaiRegistryEntry;
    paymentMemo: string;
}): {
    id: bigint;
    status: Variant_pending_approved_rejected;
    submitter: Principal;
    submittedAt: Time;
    entry: BonsaiRegistryEntry;
    paymentMemo: string;
} {
    return {
        id: value.id,
        status: from_candid_variant_n32(_uploadFile, _downloadFile, value.status),
        submitter: value.submitter,
        submittedAt: value.submittedAt,
        entry: from_candid_BonsaiRegistryEntry_n10(_uploadFile, _downloadFile, value.entry),
        paymentMemo: value.paymentMemo
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nft: null;
} | {
    tools: null;
} | {
    social: null;
} | {
    defi: null;
} | {
    gaming: null;
} | {
    wallet: null;
} | {
    commerce: null;
} | {
    exchange: null;
}): Category {
    return "nft" in value ? Category.nft : "tools" in value ? Category.tools : "social" in value ? Category.social : "defi" in value ? Category.defi : "gaming" in value ? Category.gaming : "wallet" in value ? Category.wallet : "commerce" in value ? Category.commerce : "exchange" in value ? Category.exchange : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_approved_rejected {
    return "pending" in value ? Variant_pending_approved_rejected.pending : "approved" in value ? Variant_pending_approved_rejected.approved : "rejected" in value ? Variant_pending_approved_rejected.rejected : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Category>): Array<Category> {
    return value.map((x)=>from_candid_Category_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmailSubscriber>): Array<EmailSubscriber> {
    return value.map((x)=>from_candid_EmailSubscriber_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PendingSubmission>): Array<PendingSubmission> {
    return value.map((x)=>from_candid_PendingSubmission_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BonsaiRegistryEntry>): Array<BonsaiRegistryEntry> {
    return value.map((x)=>from_candid_BonsaiRegistryEntry_n10(_uploadFile, _downloadFile, x));
}
function to_candid_BonsaiRegistryEntry_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BonsaiRegistryEntry): _BonsaiRegistryEntry {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_ExtendedUserProfile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExtendedUserProfile): _ExtendedUserProfile {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_SocialLinks_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SocialLinks): _SocialLinks {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_WalletAddresses_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WalletAddresses): _WalletAddresses {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    url: string;
    categories: Array<Category>;
    name: string;
    createdAt: Time;
    tier: bigint;
    ecosystem: string;
    description: string;
    logoUrl?: string;
}): {
    id: bigint;
    url: string;
    categories: Array<_Category>;
    name: string;
    createdAt: _Time;
    tier: bigint;
    ecosystem: string;
    description: string;
    logoUrl: [] | [string];
} {
    return {
        id: value.id,
        url: value.url,
        categories: to_candid_vec_n3(_uploadFile, _downloadFile, value.categories),
        name: value.name,
        createdAt: value.createdAt,
        tier: value.tier,
        ecosystem: value.ecosystem,
        description: value.description,
        logoUrl: value.logoUrl ? candid_some(value.logoUrl) : candid_none()
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    ratedEntries: Array<EntryRating>;
    submittedEntries: Array<bigint>;
    username: string;
    displayName: string;
    pinnedNfts: Array<{
        tokenId: bigint;
        collectionId: string;
    }>;
    socialLinks: SocialLinks;
    badges: Array<string>;
    joinedAt: Time;
    walletAddresses: WalletAddresses;
    bookmarks: Array<bigint>;
    avatarUrl?: string;
    bannerUrl?: string;
}): {
    bio: string;
    ratedEntries: Array<_EntryRating>;
    submittedEntries: Array<bigint>;
    username: string;
    displayName: string;
    pinnedNfts: Array<{
        tokenId: bigint;
        collectionId: string;
    }>;
    socialLinks: _SocialLinks;
    badges: Array<string>;
    joinedAt: _Time;
    walletAddresses: _WalletAddresses;
    bookmarks: Array<bigint>;
    avatarUrl: [] | [string];
    bannerUrl: [] | [string];
} {
    return {
        bio: value.bio,
        ratedEntries: value.ratedEntries,
        submittedEntries: value.submittedEntries,
        username: value.username,
        displayName: value.displayName,
        pinnedNfts: value.pinnedNfts,
        socialLinks: to_candid_SocialLinks_n35(_uploadFile, _downloadFile, value.socialLinks),
        badges: value.badges,
        joinedAt: value.joinedAt,
        walletAddresses: to_candid_WalletAddresses_n37(_uploadFile, _downloadFile, value.walletAddresses),
        bookmarks: value.bookmarks,
        avatarUrl: value.avatarUrl ? candid_some(value.avatarUrl) : candid_none(),
        bannerUrl: value.bannerUrl ? candid_some(value.bannerUrl) : candid_none()
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    twitter?: string;
    website?: string;
    discord?: string;
    telegram?: string;
    github?: string;
}): {
    twitter: [] | [string];
    website: [] | [string];
    discord: [] | [string];
    telegram: [] | [string];
    github: [] | [string];
} {
    return {
        twitter: value.twitter ? candid_some(value.twitter) : candid_none(),
        website: value.website ? candid_some(value.website) : candid_none(),
        discord: value.discord ? candid_some(value.discord) : candid_none(),
        telegram: value.telegram ? candid_some(value.telegram) : candid_none(),
        github: value.github ? candid_some(value.github) : candid_none()
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    btc?: string;
    eth?: string;
    sol?: string;
    hbar?: string;
}): {
    btc: [] | [string];
    eth: [] | [string];
    sol: [] | [string];
    hbar: [] | [string];
} {
    return {
        btc: value.btc ? candid_some(value.btc) : candid_none(),
        eth: value.eth ? candid_some(value.eth) : candid_none(),
        sol: value.sol ? candid_some(value.sol) : candid_none(),
        hbar: value.hbar ? candid_some(value.hbar) : candid_none()
    };
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    nft: null;
} | {
    tools: null;
} | {
    social: null;
} | {
    defi: null;
} | {
    gaming: null;
} | {
    wallet: null;
} | {
    commerce: null;
} | {
    exchange: null;
} {
    return value == Category.nft ? {
        nft: null
    } : value == Category.tools ? {
        tools: null
    } : value == Category.social ? {
        social: null
    } : value == Category.defi ? {
        defi: null
    } : value == Category.gaming ? {
        gaming: null
    } : value == Category.wallet ? {
        wallet: null
    } : value == Category.commerce ? {
        commerce: null
    } : value == Category.exchange ? {
        exchange: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Category>): Array<_Category> {
    return value.map((x)=>to_candid_Category_n4(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<BonsaiRegistryEntry>): Array<_BonsaiRegistryEntry> {
    return value.map((x)=>to_candid_BonsaiRegistryEntry_n1(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
